# Generated by Django 5.2.12 on 2026-03-23 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_article_idx_type_status_pub_and_more'),
        ('comments', '0005_commentreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'is_enable', '-creation_time'], name='idx_art_enable_time'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-creation_time'], name='idx_author_time'),
        ),
    ]
