# Generated by Django 5.2.12 on 2026-03-26 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_article_idx_type_status_pub_and_more'),
        ('comments', '0005_commentreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-creation_time'], name='idx_creation_time_desc'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', '-creation_time'], name='idx_article_creation_time'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-creation_time'], name='idx_author_creation_time'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_enable', '-creation_time'], name='idx_enable_creation_time'),
        ),
        migrations.AddIndex(
            model_name='commentreaction',
            index=models.Index(fields=['comment', 'user', 'reaction_type'], name='idx_comment_user_reaction'),
        ),
        migrations.AddIndex(
            model_name='commentreaction',
            index=models.Index(fields=['user', '-created_at'], name='idx_user_reaction_time'),
        ),
    ]
