# Generated by Django 5.2.12 on 2026-03-26 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_article_idx_type_status_pub_and_more'),
        ('comments', '0005_commentreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='idx_art_parent_enable',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'is_enable', '-id'], name='idx_article_enable_id'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment', 'is_enable', '-id'], name='idx_parent_enable_id'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-id'], name='idx_author_id'),
        ),
    ]
