# Generated by Django 5.2.12 on 2026-03-23 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogsettings_color_scheme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='idx_type_status_pub',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'type', '-pub_time'], name='idx_status_type_pub'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', '-pub_time'], name='idx_author_pubtime'),
        ),
    ]
